### PR TITLE
Replaced Ava and Ninos with jest

### PR DESCRIPTION
**Pull request by Akashic101**
This PR covers issue #11 by replacing Ava and Ninos with jest. It is not perfect yet, one test-case isn't working yet, the tests in `checkLinkStatuses.test.js` are still broken, but the rest pass with no issues.

_Also this time I didn't mess up the version-numbers :D_

### CODE REVIEW

**Comment by bradleyburgess** [comment]
Thanks, @Akashic101, I will take a look! 

> ... one test-case isn't working yet, the tests in `checkLinkStatuses.test.js` are still broken, but the rest pass with no issues.

I'd like to merge a fix that is 100% working. I'll see if I can figure out what's going on there later. 
 
> _Also this time I didn't mess up the version-numbers :D_

Haha, thank you ever so much.

**Comment by bradleyburgess** [comment]
@Akashic101, I submitted a PR to your fork to address the above issues. If you merge it in, that should be enough for me to merge your work into `main`.

**Comment by Akashic101** [comment]
PR is merged

**Comment by bradleyburgess** [comment]
@Akashic101, I did one more PR to your fork.

**Comment by Akashic101** [comment]
Has been merged as well

**Comment by bradleyburgess** [comment]
This looks ready. Thanks for your work, @Akashic101!

**Pull request merged**
